export const Members = [
    { name: "Arijit Chatterjee", photo: "ceo.jpg", designation:"Founder & CEO", email: "thelinkseller@gmail.com", linkendin: "https://www.linkedin.com/in/arijit-chatterjee-040825265", facebook: "https://www.facebook.com/arijit.chatterjee.9484?mibextid=ZbWKwL", twitter: "https://twitter.com/thelinkseller?t=C5XrdUtF9y-SrUAiB7mFgA&amp;s=09", skype: "live:.cid.d24df54365a0dd3" },
    { name: "Sourav Dutta", photo: "sourav.png", designation:"SEO Manager", email: "Souravdutta.thelinkseller@gmail.com", linkendin: "https://www.linkedin.com/in/sourav-dutta-78079b265", facebook: "https://www.facebook.com/prya.dey.96?mibextid=ZbWKwL", twitter: "https://twitter.com/SouravD05572240?t=yUdhdZfeDrw8SwjmtdTDFA&amp;s=08", skype: "" },
    { name: "Avijit Kundu", photo: "avijit.png", designation:"SEO Team Lead", email: "avijitkundu.linkseller@gmail.com", linkendin: "https://www.linkedin.com/in/avijit-kundu-9947521aa", facebook: "https://www.facebook.com/profile.php?id=100088119560312", twitter: "https://twitter.com/Avijittls?t=tUNS1Dtw0GLI_8oR6_49-w&amp;s=09", skype: "live:.cid.9efb8fcf0625e753" },
    { name: "Kuldip Roy", photo: "kuldip.png", designation:"Link Building Manager", email: "kuldip.consultant@gmail.com", linkendin: "https://www.linkedin.com/in/kuldip-roy-940408266", facebook: "https://www.facebook.com/profile.php?id=100090575697528", twitter: "https://twitter.com/KuldipR54534840?t=JxemGmgIhGb5Z1eNM_WmBg&amp;s=09", skype: "" },
    { name: "Gobinda Paramanik", photo: "govinda.png", designation:"Content Marketing Manager", email: "gobinda.thelinkseller@gmail.com", linkendin: "https://www.linkedin.com/in/gobinda-paramanik-110457265", facebook: "https://www.facebook.com/gobinda.paramanik.1?mibextid=ZbWKwL", twitter: "https://twitter.com/GobindaTLSLtd?t=wKAmQklfVhT3cxVTISJP-Q&amp;s=09", skype: "" },
    { name: "Banku Deghuria", photo: "banku.png", designation:"SEO Expert", email: "banku.thelinkseller@gmail.com", linkendin: "https://www.linkedin.com/in/banku-deghuria-830970265", facebook: "https://www.facebook.com/banku.deghuria?mibextid=ZbWKwL", twitter: "https://twitter.com/BankuTLS?t=ERQCx7ImPQzLeA52fEnaig&amp;s=08", skype: "" },
    { name: "Rahul Roy", photo: "rahul.png", designation:"Digital Marketing Consultant", email: "rahul.thelinkseller@gmail.com", linkendin: "https://www.linkedin.com/in/rahul-roy-3677a1265", facebook: "https://www.facebook.com/bindas.veki", twitter: "https://twitter.com/RahulTLSLtd?t=wmGLtj-GakcDg9-7hoLGng&amp;s=09", skype: "" },
    { name: "Pradip Musib", photo: "pradip.png", designation:"Marketing & sales Specialist", email: "thelinkseller.pradip@gmail.com", linkendin: "https://www.linkedin.com/in/pradip-musib/", facebook: "https://www.facebook.com/pradip.musib.1/", twitter: "", skype: "live:.cid.9567d7b66e34cba8" },
    // { name: "NAME", photo: "photo", designation:"desg", email: "email", linkendin: "linkedin", facebook: "facebook", twitter: "twitter", skype: "skype" },
];
